# Generated by Django 2.2.6 on 2019-10-13 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game_type', models.CharField(choices=[('ticktactoe', 'Ticktactoe'), ('nim', 'Nim'), ('sudoku', 'Sudoku')], default='ticktactoe', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_first_player', models.BooleanField(default=False)),
                ('is_winner', models.BooleanField(default=False)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_played', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_agent', models.CharField(blank=True, max_length=254, null=True)),
                ('channel', models.CharField(blank=True, choices=[('app', 'App'), ('web', 'Web'), ('mobile_web', 'Mobile Web')], db_index=True, max_length=10, null=True)),
                ('matches', models.ManyToManyField(related_name='player_list', through='games.MatchPlayerMembership', to='games.Match')),
                ('user_orig', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match_played', models.IntegerField(default=0)),
                ('match_won', models.IntegerField(default=0)),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='games.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='matchplayermembership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Player'),
        ),
        migrations.AddField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='players', through='games.MatchPlayerMembership', to='games.Player'),
        ),
        migrations.AddConstraint(
            model_name='matchplayermembership',
            constraint=models.UniqueConstraint(fields=('player', 'match'), name='unique appversion'),
        ),
    ]
